# This playbook needs the package python2-boto
---
- hosts: localhost
  connection: local
  become: False
  gather_facts: False

  vars_files:
    - "vars.yml"

  environment:
    AWS_ACCESS_KEY: "{{ aws_access_key }}"
    AWS_SECRET_KEY: "{{ aws_secret_key }}"

  tasks:
    - name: Provision a instance
      ec2:
         key_name: "PTI_KeyPair"
         # group: test
         region: "{{ region }}"
         instance_type: "t2.micro"
         image: "{{ ami_id }}"
         wait: true
         exact_count: 1
         count_tag:
            Name: MineTheTag
         instance_tags:
            Name: MineTheTag
      register: ec2

    - name: Add all instance public IPs to host group
      add_host: hostname={{ item.public_ip }} groups=ec2hosts
      with_items: "{{ ec2.instances }}"

    - name: Update dns record
      uri:
        url: https://dyn.dns.he.net/nic/update
        method: POST
        body: "hostname={{ domain }}&password={{ he_dns_password }}&myip={{ item.public_ip }}"
        body_format: raw
        return_content: yes

      with_items: "{{ ec2.instances }}"
